# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-03 13:00
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('num', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('name_jp', models.CharField(max_length=10)),
                ('name_en', models.CharField(max_length=20)),
                ('effect', models.TextField()),
                ('effect_battle', models.TextField()),
                ('effect_map', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EggGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Evolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('way', models.CharField(max_length=20)),
                ('condition', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Gen',
            fields=[
                ('num', models.SmallIntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Kind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('num', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('name_jp', models.CharField(max_length=20)),
                ('name_en', models.CharField(max_length=30)),
                ('power', models.SmallIntegerField()),
                ('accuracy', models.SmallIntegerField()),
                ('pp', models.SmallIntegerField()),
                ('effect', models.TextField()),
                ('effect_battle', models.TextField()),
                ('effect_map', models.TextField()),
                ('priority', models.SmallIntegerField()),
                ('z_stone', models.CharField(max_length=10)),
                ('z_move', models.CharField(max_length=10)),
                ('z_power', models.CharField(max_length=20)),
                ('gen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qAq.Gen')),
                ('kind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qAq.Kind')),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('num', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('name_jp', models.CharField(max_length=10)),
                ('name_en', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=20)),
                ('egg_step', models.SmallIntegerField()),
                ('male_rate', models.FloatField()),
                ('female_rate', models.FloatField()),
                ('catch', models.SmallIntegerField()),
                ('happiness', models.SmallIntegerField()),
                ('expto100', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PokemonAbility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.CharField(max_length=20)),
                ('is_hidden', models.BooleanField()),
                ('ability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qAq.Ability')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qAq.Pokemon')),
            ],
        ),
        migrations.CreateModel(
            name='PokemonClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PokemonForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.CharField(max_length=20)),
                ('is_normal', models.BooleanField()),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('stats', django.contrib.postgres.fields.jsonb.JSONField()),
                ('stats_get', django.contrib.postgres.fields.jsonb.JSONField()),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qAq.Pokemon')),
            ],
        ),
        migrations.CreateModel(
            name='PokemonMove',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('way', models.CharField(max_length=20)),
                ('condition', models.CharField(max_length=10)),
                ('form', models.CharField(max_length=20)),
                ('move', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qAq.Move')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qAq.Pokemon')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
            ],
        ),
        migrations.AddField(
            model_name='pokemonform',
            name='types',
            field=models.ManyToManyField(to='qAq.Type'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='abilities',
            field=models.ManyToManyField(through='qAq.PokemonAbility', to='qAq.Ability'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='egg_groups',
            field=models.ManyToManyField(to='qAq.EggGroup'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='evolutions',
            field=models.ManyToManyField(through='qAq.Evolution', to='qAq.Pokemon'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='gen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qAq.Gen'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='moves',
            field=models.ManyToManyField(through='qAq.PokemonMove', to='qAq.Move'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='pokemon_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qAq.PokemonClass'),
        ),
        migrations.AddField(
            model_name='move',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qAq.Type'),
        ),
        migrations.AddField(
            model_name='evolution',
            name='evolution_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evolution_from_set', to='qAq.Pokemon'),
        ),
        migrations.AddField(
            model_name='evolution',
            name='evolution_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evolution_to_set', to='qAq.Pokemon'),
        ),
        migrations.AddField(
            model_name='ability',
            name='gen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qAq.Gen'),
        ),
    ]
