# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-03 13:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qAq', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ability',
            old_name='num',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='move',
            old_name='num',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='pokemon',
            old_name='num',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='evolution',
            name='evolution_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_evolution_from_set', to='qAq.Pokemon'),
        ),
        migrations.AlterField(
            model_name='evolution',
            name='evolution_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_evolution_to_set', to='qAq.Pokemon'),
        ),
    ]
