# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qaq', '0002_loaddata'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordDic',
            fields=[
                ('word', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('tag', models.CharField(max_length=10)),
            ],
        ),
    ]
