# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 03:10
from __future__ import unicode_literals

from django.db import migrations
from qaq.aldnoah import router


def register_domainuri(apps, schema_editor):
    router.register_domainuri('yamls/router.yaml')


class Migration(migrations.Migration):

    dependencies = [
        ('qaq', '0002_loaddata'),
    ]

    operations = [
        migrations.RunPython(register_domainuri)
    ]
